site_name: DCSC Wiki
site_url: https://dcs-c.github.io
plugins:
  - search
  - awesome-nav
theme:
  name: material
  palette:
    scheme: brown
    primary: black
  font:
    text: IBM Plex Sans KR
markdown_extensions:
  - toc:
      permalink: true
      slugify: !!python/name:markdown.extensions.toc.slugify_unicode
extra_javascript:
    - js/copy-anchors.js

